# Generated by Django 3.0.5 on 2020-04-18 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(default='NA', max_length=200)),
                ('lName', models.CharField(default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(default='NA', max_length=200)),
                ('lName', models.CharField(default='NA', max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('emailAddress', models.CharField(default='NA', max_length=200)),
                ('dateAquired', models.DateField(default=datetime.date(2020, 4, 18))),
                ('dateLastOrder', models.DateField(default=datetime.date(2020, 4, 18))),
                ('outstandingOrder', models.CharField(default='No', max_length=5)),
                ('dateOfBirth', models.DateField(default=datetime.date(2020, 4, 18))),
                ('agentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplecustomer.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(default='NA', max_length=200)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplecustomer.Customer')),
            ],
        ),
    ]
