# Generated by Django 3.0.5 on 2020-04-20 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplecustomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='EstimatedDelivery',
            field=models.DateField(default=datetime.date(2020, 4, 20)),
        ),
        migrations.AddField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.date(2020, 4, 20)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateAquired',
            field=models.DateField(default=datetime.date(2020, 4, 20)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateLastOrder',
            field=models.DateField(default=datetime.date(2020, 4, 20)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(2020, 4, 20)),
        ),
    ]
